### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by solbadguy2010** [vrkttr/homebridge-vicare#1]
Hi, first thank you for the plugin.
At first i had some problems creating the Access Token. I had to create an "Client" first and then wait some minutes to be able to generate a token.

Afterwards the plugin reports: "[ViCareThermostat] Retrieved all necessary IDs."

Then i find one new thermostat in my Home App named "ViCareThermostat" that states "no response" and has no value.

Whats also missing for me are all my room Thermostats

**Comment by vrkttr** [comment]
Please enable the Debug mode via Config.

**Comment by vrkttr** [comment]
should be fixed now.

**Comment by solbadguy2010** [comment]
Sadly not. He added some Sensors, but nothing changed in Home App

[homebridge.log (2).txt](https://github.com/user-attachments/files/15614079/homebridge.log.2.txt)

Also the Room Thermostats are not visible in the log

**Comment by solbadguy2010** [comment]
with .10 i start to get errors and HB Service crash:

[06/06/2024, 13:13:42] TypeError: Cannot read properties of undefined (reading 'properties')
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-vicare/index.js:258:51)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-vicare/node_modules/request/request.js:185:22)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vicare/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:519:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vicare/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by vrkttr** [comment]
Thanks for your logs! I've tried a different approach to handle the devices. Please update to version 1.1.0.

Now, you can choose which types you want to integrate.

To proceed:

1. Disable Homebridge-ViCare.
2. Update the plugin.
3. Reactivate Homebridge-ViCare.

**Comment by solbadguy2010** [comment]
Oh, wait! They are temp sensors now! I see them :-)

How can i expose the seperate room thermostats to homekit?
