### ISSUE TITLE
Can't Connect to Vissmann Developer Portal

### ISSUE THREAD

**Issue by darkdevil373** [vrkttr/homebridge-vicare#10]
Hi all,

i try connect my heating System to homebridge.
The Config.json is edited, an homebgrige shows in the log the Url to Open the 2 Factor:

https://iam.viessmann.com/idp/v3/authorize?client_id=XXXXXXXXXXXXXXXXXXXXXXXXXX&redirect_uri=http%3A%2F%2F192.168.123.43%3A4200&scope=IoT%20User%20offline_access&response_type=code&code_challenge_method=S256&code_challenge=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

in other issues i have found, that there is an error, an i try to edit the URL:

https://iam.viessmann.com/idp/v3/authorize?client_id=XXXXXXXXXXXXXXXXXXXXXXXX&redirect_url=http%3A%2F%2F192.168.123.43%3A4200&scope=IoT%20Userresponse_type=code&code_challenge_method=S256&code_challenge=XXXXXXXXXXXXXXXXXXXXXXX

when i open the edited url, i get an authentication webseite from Vissmann, but after i login with my credentials 

The Website shows

"Systemfehler. Bitte versuchen Sie es später." - "System error. Please try again later.
"

**Comment by dvbcheck** [comment]
**Same here:
Config.json:**

            "platform": "ViCareThermostatPlatform",
            "name": "ViCareThermostat",
            "clientId": "f75b7473f9e66035257d3720XXXXXXXX",
            "apiEndpoint": "https://api.viessmann.com/iot/v1",
            "devices": [
                {
                    "name": "Supply temperature",
                    "feature": "heating.circuits.0.sensors.temperature.supply",
                    "deviceId": "0"
                },
                {
                    "name": "Main DHW temperature",
                    "feature": "heating.dhw.temperature.main",
                    "deviceId": "0"
                }
            ],
            "_bridge": {
                "username": "0E:36:84:85:14:46",
                "port": 41849

**Status in HomeBridge V. 1.8.4:**

[06/10/2024, 08:45:57] [ViCareThermostat] Using redirect URI: http://192.168.2.2:4200
[06/10/2024, 08:45:57] [ViCareThermostat] Opening browser for authentication: https://iam.viessmann.com/idp/v3/authorize?client_id=f75b7473f9e66035257d3720XXXXXXXX&redirect_uri=http%3A%2F%2F192.168.2.2%3A4200&scope=IoT%20User%20offline_access&response_type=code&code_challenge_method=S256&code_challenge=HWTnRnH55JjEmM0wz2EaBaOrXp435DwjbAwsrRFJS5A

**
<img width="930" alt="Bildschirmfoto 2024-10-06 um 08 35 26" src="https://github.com/user-attachments/assets/e1947304-64da-43a3-9d56-d410c48d69a8">
<img width="606" alt="Bildschirmfoto 2024-10-06 um 08 51 57" src="https://github.com/user-attachments/assets/3b4c4321-da0d-4745-98ae-6bbdb8f6c4a1">
<img width="1317" alt="Bildschirmfoto 2024-10-06 um 08 52 20" src="https://github.com/user-attachments/assets/82ebfd53-0bcf-4c58-a429-64960f6a0a14">
<img width="617" alt="Bildschirmfoto 2024-10-06 um 08 34 16" src="https://github.com/user-attachments/assets/219d441f-a312-49fa-8d7c-ad8689ba6b95">**

{"error":"invalid_request", "error_description":"Invalid redirection URI."}

**Comment by dvbcheck** [comment]
VPN causes error in my case.

**Comment by ankraft** [comment]
> https://iam.viessmann.com/idp/v3/authorize?client_id=0f55dee79e27498e9fa4a54928xxxxxx&redirect_uri=http%3A%2F%2F10.0.0.20%3A4200&scope=IoT%20User%20offline_access&response_type=code&code_challenge_method=S256&code_challenge=jz8Qv4bged71IOP9V6aS845YAt-r9_C0KaZbavfivkc

The following worked for me:
In the opened browser tab I replaced in the URL the `...=http%3A%2F%2F...` with `...=http://...` .

**Comment by corneloaie** [comment]
I have the same issue? Any solution to this?

**Comment by rebellionflash** [comment]
> I have the same issue? Any solution to this?

I also have problems with authentication 

error | "invalid_request"
error_description | "Invalid redirection URI."

**Comment by ffflorian** [comment]
Hi, can you try with version 2.10.2 again?

**Comment by SchoppAx** [comment]
I tried version 2.10.6. Same issue:
https://iam.viessmann-climatesolutions.com/idp/v3/authorize?client_id=b5b1dfb175f0849a74a0c847xxxxxxxx&redirect_uri=http%3A%2F%2F10.0.0.48%3A4200&scope=IoT+User+offline_access&response_type=code&code_challenge_method=S256&code_challenge=cjv7kVqyCeCHYQ3yRkU1yNwUO1rjrjlLgYYYdXJiG5s
```json
{"error":"invalid_request", "error_description":"Invalid redirection URI."}
```

Change the Url to:
https://iam.viessmann-climatesolutions.com/idp/v3/authorize?client_id=b5b1dfb175f0849a74a0c847xxxxxxxx&redirect_uri=http%3A%2F%2F10.0.0.48%3A4200%2F&scope=IoT+User+offline_access&response_type=code&code_challenge_method=S256&code_challenge=QW0pyNBCUCWSVCpQTDqXICEZE9KGuExW8KCoJieK8Iw

After successfull authorization:
```
[7/15/2025, 9:33:29 PM] [ViCareThermostat] Error exchanging code for token: Error: {
  "error": "invalid_grant",
  "error_description": "Invalid grant"
}
    at ViCareThermostatPlatform.<anonymous> (file:///homebridge/node_modules/homebridge-vicare/src/ViCareThermostatPlatform.ts:255:15)
    at Generator.next (<anonymous>)
    at fulfilled (file:///homebridge/node_modules/homebridge-vicare/dist/ViCareThermostatPlatform.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[7/15/2025, 9:33:29 PM] [ViCareThermostat] Error during authentication: Error: {
  "error": "invalid_grant",
  "error_description": "Invalid grant"
}
    at ViCareThermostatPlatform.<anonymous> (file:///homebridge/node_modules/homebridge-vicare/src/ViCareThermostatPlatform.ts:255:15)
    at Generator.next (<anonymous>)
    at fulfilled (file:///homebridge/node_modules/homebridge-vicare/dist/ViCareThermostatPlatform.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[7/15/2025, 9:33:29 PM] Error: {
  "error": "invalid_grant",
  "error_description": "Invalid grant"
}
    at ViCareThermostatPlatform.<anonymous> (file:///homebridge/node_modules/homebridge-vicare/src/ViCareThermostatPlatform.ts:255:15)
    at Generator.next (<anonymous>)
    at fulfilled (file:///homebridge/node_modules/homebridge-vicare/dist/ViCareThermostatPlatform.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

After restart:
```
[7/15/2025, 9:33:40 PM] [ViCareThermostat] Refresh token invalid: Error: No token found
    at ViCareThermostatPlatform.<anonymous> (file:///homebridge/node_modules/homebridge-vicare/src/ViCareThermostatPlatform.ts:74:17)
    at Generator.next (<anonymous>)
    at fulfilled (file:///homebridge/node_modules/homebridge-vicare/dist/ViCareThermostatPlatform.js:4:58)
[7/15/2025, 9:33:40 PM] [ViCareThermostat] Starting authentication process...
[7/15/2025, 9:33:40 PM] [ViCareThermostat] Click this link for authentication: https://iam.viessmann-climatesolutions.com/idp/v3/authorize?client_id=b5b1dfb175f0849a74a0c847xxxxxxxx&redirect_uri=http%3A%2F%2F10.0.0.48%3A4200&scope=IoT+User+offline_access&response_type=code&code_challenge_method=S256&code_challenge=RjUFiosadrGQ3WhS0SudEwg91tbjROR1Ji5FJ6_NoDM
